<a href="https://colab.research.google.com/github/caro0020/Parcial04--Ramos-Santos-Iveth-Carolina-1713092019/blob/main/ClaveE_Analisis_de_asociacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Librerias necesarias

In [1]:
import pandas as pd
import numpy as np
from itertools import combinations

In [2]:
ruta_archivo = "https://raw.githubusercontent.com/caro0020/Parcial04--Ramos-Santos-Iveth-Carolina-1713092019/refs/heads/main/clave_E_asociacion.csv"
df = pd.read_csv(ruta_archivo)
df.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,E-T0001,E-C0068,2026-01-01,Tecnico,Calculadora,1,App
1,E-T0001,E-C0068,2026-01-01,Libros,Novela,1,App
2,E-T0001,E-C0068,2026-01-01,Arte,Pinceles,1,App
3,E-T0001,E-C0068,2026-01-01,Tecnico,Regla,1,App
4,E-T0002,E-C0056,2026-01-22,Papeleria,Lapiz,1,Web

Validar dimensiones

In [3]:
df.shape

(605, 7)

In [4]:
df.columns

Index(['transaccion_id', 'cliente_id', 'fecha', 'categoria', 'item',
       'cantidad', 'canal'],
      dtype='object')

In [5]:
df.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,E-T0001,E-C0068,2026-01-01,Tecnico,Calculadora,1,App
1,E-T0001,E-C0068,2026-01-01,Libros,Novela,1,App
2,E-T0001,E-C0068,2026-01-01,Arte,Pinceles,1,App
3,E-T0001,E-C0068,2026-01-01,Tecnico,Regla,1,App
4,E-T0002,E-C0056,2026-01-22,Papeleria,Lapiz,1,Web

Revisar tipos de datos

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaccion_id  605 non-null    object
 1   cliente_id      605 non-null    object
 2   fecha           605 non-null    object
 3   categoria       605 non-null    object
 4   item            605 non-null    object
 5   cantidad        605 non-null    int64
 6   canal           604 non-null    object
dtypes: int64(1), object(6)
memory usage: 33.2+ KB

Valores nulos

In [7]:
df.isnull().sum()

transaccion_id    0
cliente_id        0
fecha             0
categoria         0
item              0
cantidad          0
canal             1
dtype: int64

Revision de duplicados

In [8]:
df.duplicated().sum()

np.int64(1)

Estadistica descriptiva

In [9]:
df.describe()

         cantidad
count  605.000000
mean     1.403306
std      0.708970
min      1.000000
25%      1.000000
50%      1.000000
75%      2.000000
max      4.000000

In [27]:
df.describe()

         cantidad
count  605.000000
mean     1.403306
std      0.708970
min      1.000000
25%      1.000000
50%      1.000000
75%      2.000000
max      4.000000

In [39]:
print(df.columns.tolist())

['transaccion_id', 'cliente_id', 'fecha', 'categoria', 'item', 'cantidad', 'canal']

In [44]:
columnas_asociacion = ["frecuencia_compra", "uso_app", "satisfaccion"]